### ISSUE TITLE
MODULE_NOT_FOUND Running any pnpm command

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [pnpm/pnpm#2923]
### Actual behavior:
pnpm -v
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'C:\Users\[UserName]\AppData\Roaming\npm\pnpm-global\4\node_modules\pnpm\bin\pnpm.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

### Additional information:

 - `node -v` prints: 12.19.0
 - Windows, OS X, or Linux?: Windows 10

**Comment by artemirq** [comment]
I have the same problem with 5.9.0. But 5.8.0 works fine for me. Try install 5.8.0 again and run `pnpm i`

**Comment by diachedelic** [comment]
I can confirm this is a problem with 5.9.0, 5.8.0 works fine.

**Comment by artemirq** [comment]
Newly released 5.9.3 with fixes working fine for me

**Comment by cyrus-za** [comment]
Running into this on 6.14.5 but only half the time. Rerunning `pnpm i` fixes it (sometimes multiple times required)

**Comment by zkochan** [comment]
Try the latest pnpm. We fixed a similar issue in 6.15.0 https://github.com/pnpm/pnpm/pull/3768

**Comment by T1mL3arn** [comment]
Get the similar problem. Was trying to upgrade pnpm to 6.17.1 and something broke. Now I get this for `pnpm` command

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\User\AppData\Roaming\npm\pnpm-global\5\node_modules\pnpm\bin\pnpm.cjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Updating `npm` to the latest (`8.1.0` at this moment) and installing `pnpm` with `npm install -g pnpm` didn't fix the problem.

**Comment by Sepush** [comment]
the same on `windows10` `git bash` `node16`
![image](https://user-images.githubusercontent.com/39197136/162659693-74859198-e06c-4f55-979f-f8dd5f27852f.png)

**Comment by sunnylost** [comment]
> the same on `windows10` `git bash` `node16` ![image](https://user-images.githubusercontent.com/39197136/162659693-74859198-e06c-4f55-979f-f8dd5f27852f.png)

I got the same error, you should try `pnpm i -g pnpm`, this solved my problem.

**Comment by ziedHamdi** [comment]
I fixed that running a new pnpm install:
iwr https://get.pnpm.io/install.ps1 -useb | iex (on windows, see equivalent on other platforms in official docs)
