### ISSUE TITLE
pnpm won't worked with node-newrelic.

### ISSUE THREAD

**Issue by AilisObrian** [pnpm/pnpm#397]
### pnpm version:

pnpm 0.39.0 (but I think all versions of pnpm.)
### Code to reproduce the issue:
- Install packages with pnpm (`$ pnpm install`)
- Launch node app with node-newrelic.
### Expected behavior:
- Successfully launched within seconds.
### Actual behavior:
- [node-newrelic try to walk-through all `node_module` packages](https://github.com/newrelic/node-newrelic/blob/master/lib/environment.js#L259-L314)
  - But fell down to the symbolic hell (which well-gardened by pnpm), and It won't return.
### Bypass way:
- Launch with `NEW_RELIC_ENABLED=false`
### Additional information:

npm 3.10.3
Node v6.7.0
OSX El Capitan 10.11.6

**Comment by AilisObrian** [comment]
It's not pnpm's bug, but I want to share this with you guys and find out better solutions for this.
Thanks all.

**Comment by AilisObrian** [comment]
```json
{"v":0,"level":30,"name":"newrelic","hostname":"OBrians-MacBook-Pro.local","pid":18457,"time":"2016-10-04T10:34:04.658Z","msg":"Could not load /Users/obrian/projects/MintCare/global_server/node_modules/eslint/node_modules/escope/node_modules/es6-map/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/package.json for environment scan","component":"environment"}
```

**Comment by iamstarkov** [comment]
hi @AilisObrian, thank you for issue. can you clarify it a bit.
on my machine `pnpm i newrelic` seems to be working:

```
➜  compose-function git:(master) pnpm i newrelic        
  newrelic                                                         1.30.4 ✓ 
  concat-stream ^1.5.0                                              1.5.2 ✓ 
  https-proxy-agent ^0.3.5                                          0.3.6 ✓ 
  json-stringify-safe ^5.0.0                                        5.0.1 ✓ 
  readable-stream ^1.1.13                                          1.1.14 ✓ 
  semver ^4.2.0                                                     4.3.6 ✓ 
  yakaa ^1.0.1                                                      1.0.1 ✓ 

> compose-function@3.0.3 prepublish /Users/vlasta/projects/compose-function
> npm run --silent clean && npm run transpile

Saved working directory and index state On master: `npm run clean` trash can
HEAD is now at 35e9f86 fix test
Removing index.js
Removing npm-debug.log
Removing pnpm-debug.log
HEAD is now at 35e9f86 fix test

clean: Uncommitted and ignored files have been moved to gitâs stash. To restore them run `git stash pop --quiet; git checkout .gitignore`.

> compose-function@3.0.3 transpile /Users/vlasta/projects/compose-function
> babel module --out-dir .

module/index.js -> index.js
➜  compose-function git:(master) 
```

**Comment by AilisObrian** [comment]
@iamstarkov `pnpm install newrelic` works great!
But when I tried to use `newrelic` package, It HANGED by pnpm's packages symbolic structure.
You can see the logs which I attached above.

**Comment by zkochan** [comment]
I think this might be related to the [pnpm install doesn't get the job done when node_modules is cached by Travis CI](https://github.com/rstacruz/pnpm/issues/315). Seems like pnpm has some circular linking...

**Comment by zkochan** [comment]
@AilisObrian could you please create a sample repo? Seems like I don't know how to use newrelic.  I always get this error 

```
/home/zkochan/src/test/node-newrelic/node_modules/.store/newrelic@1.30.5/_/lib/config.js:231
  throw new Error(
  ^

Error: Unable to find New Relic module configuration. A default
configuration file can be copied from /home/zkochan/src/test/node-newrelic/node_modules/.store/newrelic@1.30.5/_/lib/config.default.js
and put at /home/zkochan/src/test/node-newrelic/examples/http/simple/newrelic.js.
    at _failHard (/home/zkochan/src/test/node-newrelic/node_modules/.store/newrelic@1.30.5/_/lib/config.js:231:9)
    at Function.initialize (/home/zkochan/src/test/node-newrelic/node_modules/.store/newrelic@1.30.5/_/lib/config.js:1099:25)
    at Object.<anonymous> (/home/zkochan/src/test/node-newrelic/node_modules/.store/newrelic@1.30.5/_/lib/logger.js:18:37)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```


even when using the examples from the newrelic repo

**Comment by AilisObrian** [comment]
@zkochan Oh! you can just add this `newrelic.js` at the root of your project directory.
```javascript
'use strict';
exports.config = {
};
```
and run it.

**Comment by zkochan** [comment]
@AilisObrian good news, I can fix it. However, only for Node.js >= 6.3.0. And you'll have to run Node with the `--preserve-symlinks` option. (if you will be running the application via `npm run`, the option will be added automatically to the binstub files)

**Comment by zkochan** [comment]
after looking into it deeper, I realized that it is impossible to avoid circular symlinks in pnpm.

We can cut the circle because the other packages can require any package from the circular dependency. Whereas if we break the circle only one entry point to it will work...

This can be fixed only in newrelic

**Comment by iamstarkov** [comment]
wait, circular deps are fixed in nodejs land, arent they?
https://nodejs.org/api/modules.html#modules_cycles

**Comment by zkochan** [comment]
This will have to be rechecked with pnpm v0.46. I think I have removed all circular deps. They are not needed anymore with the new store design

**Comment by iamstarkov** [comment]
@AilisObrian can you reproduce this issue with latest pnpm?

**Comment by AilisObrian** [comment]
@iamstarkov @zkochan double checked with @0.47.0 but still happened.

**Comment by zkochan** [comment]
Seems like circles can still appear in dependencies with peer dependencies.

**Comment by zkochan** [comment]
@AilisObrian this is solved in [v0.51.1](https://github.com/pnpm/pnpm/releases/tag/v0.51.1). It has a structural change in node_modules that completely avoids circular symlinks.
