### ISSUE TITLE
Non-deterministic install

### ISSUE THREAD

**Issue by JanJakes** [pnpm/pnpm#5106]
I discovered a case where `pnpm install` doesn't behave deterministically — when being run again and again, a package (`promise-inflight`) is sometimes added and sometimes removed, resulting in changes in `pnpm-lock.yaml`.

I'm linking [a repository](https://github.com/JanJakes/pnpm-nondeterministic-install) with the issue reproduction. Note that there are many missing peer deps as I was trying to cut down the dependencies and still reproduce the issue.

### pnpm version:
7.6.0

### Code to reproduce the issue:
https://github.com/JanJakes/pnpm-nondeterministic-install

### Expected behavior:
No matter how many times I run `pnpm install` consecutively, there should be no changes in `pnpm-lock.yaml` and `node_modules`.

### Actual behavior:
When `pnpm install` is being run repeatedly, a package keeps being randomly added and removed.

### Additional information:
All details are in the readme of the issue reproduction: https://github.com/JanJakes/pnpm-nondeterministic-install

**Comment by gluxon** [comment]
Hi @JanJakes, are you using JFrog Artifactory by any chance? I think this is an instance of https://github.com/pnpm/pnpm/issues/5004 if so.

See https://www.jfrog.com/jira/browse/RTFACT-27265 for the Artifactory issue.

**Comment by JanJakes** [comment]
Hi @gluxon, I don't know what JFrog Artifactory is 😄 But no, I'm not using it. See the reproduction repo and the README in there — it's really all that's needed to reproduce the issue so I don't think it's related to the thread you've linked.

**Comment by gluxon** [comment]
Thanks for checking @JanJakes. That is interesting. I'm realizing you do have a different issue since the existing reference to `promise-inflight` has `peerDependenciesMeta`.

https://github.com/JanJakes/pnpm-nondeterministic-install/blob/bac7f2c8b3e69af6841bb5bab5c19882f8ef686c/pnpm-lock.yaml#L7854-L7861

As far as I can tell, adding the `_bluebird@3.7.2` peers suffix to `promise-inflight` is correct. Surprised there's instances where pnpm won't see that peer dependency.

```
  /cacache/12.0.4:
    resolution: {integrity: sha512-a0tMB40oefvuInr4Cwb3GerbL9xTj1D5yg0T5xrjGCGyfvbxseIXX7BAO/u/hIXdafzOI5JC3wDwHyf24buOAQ==}
    dependencies:
      bluebird: 3.7.2
      chownr: 1.1.4
      figgy-pudding: 3.5.2
      glob: 7.2.3
      graceful-fs: 4.2.9
      infer-owner: 1.0.4
      lru-cache: 5.1.1
      mississippi: 3.0.0
      mkdirp: 0.5.5
      move-concurrently: 1.0.1
      promise-inflight: 1.0.1
      rimraf: 2.7.1
      ssri: 6.0.2
      unique-filename: 1.1.1
      y18n: 4.0.3
    dev: true
```

I'll let the maintainers comment. Thanks for creating such a great repro.

**Comment by JanJakes** [comment]
@gluxon Thanks for looking into it! I guess saying that `promise-inflight` keeps being added and removed was not exact — maybe it's more like it keeps being added with and without the `bluebird` part:

<img width="1033" alt="181184226-57174c22-ace8-4e4a-bda8-ff21a2e607fd" src="https://user-images.githubusercontent.com/141436/181440907-a5e69953-f080-4592-ab6b-ce9c20bbdb06.png">

I was trying to cut down the deps as much as possible (we have much more than in the repro) but at some point it seems that it no longer happens when I remove even more than in the repro. Running `pnpm why promise-inflight` reveals that many subdependencies require it.

The lockfile in this state is probably important. Deleting it and installing the packages again may result in a different (and stable) install.

As a side note, it seems that ussing the rolling range (`"workspace-1": "workspace:^"`) in workspace 2 causes `pnpm` to always resolve something, instead of skipping that step when nothing changed.

**Comment by JanJakes** [comment]
I forgot to mention that the lockfile was generated using `pnpm import` from `package-lock.json`. Neverthless, it's a valid lockfile and the non-determinism seems to be there.

**Comment by apaniel** [comment]
I have the same issue with promise-inflight and blueBird, when I run a pnpm install it sometimes changes

**Comment by gluxon** [comment]
I noticed that [JanJakes/pnpm-nondeterministic-install](https://github.com/JanJakes/pnpm-nondeterministic-install) no longer reproduces after v7.9.0. It does reproduce on v7.8.0. A `git bisect` between these 2 versions narrowed it down to: 0321ca32a4d5cb858a53f519dff677f04ea174de

The removal of parallelism there probably made this repro more deterministic, but I think the problem still exists in general. I've seen it on 7.13.5 in one of my repos.

@apaniel What version of pnpm do you see the problem on?

**Comment by apaniel** [comment]
@gluxon I can reproduce in latest 7.27.0

**Comment by gluxon** [comment]
Haven't nailed down exactly what's happening but getting close. Adding some debugging notes for myself.

## Theory

The `promise-inflight` peer dependency on `bluebird` comes from the Yarn compatibility database. [`yarnpkg-extensions/sources/index.ts#`](https://github.com/yarnpkg/berry/blob/9b3f92b88753d58a12bf1aac637b2c4fcb62f4a8/packages/yarnpkg-extensions/sources/index.ts#L116-L121).

```ts
{
  [`promise-inflight@*`, {
    peerDependenciesMeta: {
      [`bluebird`]: optionalPeerDep,
    },
  }],
}
```

I'm guessing there are cases where `cacache` is resolved without the incompatibility patches to `promise-inflight`.

## Logging

Logging `{ nodeId, node }` in `resolvePeersOfNode` here.

https://github.com/pnpm/pnpm/blob/761be978b2ed70a5337eaab14e13dab103a6cf93/packages/resolve-dependencies/src/resolvePeers.ts#L188

### Correct (`inflight-promise` has peer dep)

```yaml
{
  nodeId: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>',
  node: {
    children: {
      bluebird: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/bluebird/3.7.2>',
      chownr: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/chownr/1.1.4>',
      'figgy-pudding': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/figgy-pudding/3.5.2>',
      glob: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/glob/7.2.3>',
      'graceful-fs': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/graceful-fs/4.2.9>',
      'infer-owner': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/infer-owner/1.0.4>',
      'lru-cache': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/lru-cache/5.1.1>',
      mississippi: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mississippi/3.0.0>',
      mkdirp: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mkdirp/0.5.5>',
      'move-concurrently': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/move-concurrently/1.0.1>',
      'promise-inflight': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>',
      rimraf: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/rimraf/2.7.1>',
      ssri: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/ssri/6.0.2>',
      'unique-filename': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/unique-filename/1.1.1>',
      y18n: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/y18n/4.0.3>'
    },
    depth: 4,
    installable: true,
    resolvedPackage: {
      additionalInfo: [Object],
      depPath: '/cacache/12.0.4',
      dev: false,
      fetchingBundledManifest: [AsyncFunction (anonymous)],
      fetchingFiles: [AsyncFunction (anonymous)],
      filesIndexFile: '/Users/gluxon/Library/pnpm/store/v3/files/6b/4b4c078d2879fbee227af80b06f719eadb2fdc538f50f9ca0d13e71ae31821b27ef6f1b1e2175fb0403bfbbf8485dd69fcce239242df00f01f27f6e1bb8e01-index.json',
      finishing: [AsyncFunction (anonymous)],
      hasBin: false,
      hasBundledDependencies: false,
      id: 'registry.npmjs.org/cacache/12.0.4',
      name: 'cacache',
      optional: false,
      optionalDependencies: Set(0) {},
      patchFile: undefined,
      peerDependencies: {},
      peerDependenciesMeta: undefined,
      prepare: false,
      prod: true,
      requiresBuild: false,
      resolution: [Object],
      version: '12.0.4'
    }
  }
}
```

### Incorrect (`inflight-promise` is missing peer dep)

```yaml
{
  nodeId: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>',
  node: {
    children: {
      bluebird: 'registry.npmjs.org/bluebird/3.7.2',
      chownr: 'registry.npmjs.org/chownr/1.1.4',
      'figgy-pudding': 'registry.npmjs.org/figgy-pudding/3.5.2',
      glob: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/glob/7.2.3>',
      'graceful-fs': 'registry.npmjs.org/graceful-fs/4.2.9',
      'infer-owner': 'registry.npmjs.org/infer-owner/1.0.4',
      'lru-cache': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/lru-cache/5.1.1>',
      mississippi: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mississippi/3.0.0>',
      mkdirp: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mkdirp/0.5.5>',
      'move-concurrently': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/move-concurrently/1.0.1>',
      'promise-inflight': 'registry.npmjs.org/promise-inflight/1.0.1',
      rimraf: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/rimraf/2.7.1>',
      ssri: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/ssri/6.0.2>',
      'unique-filename': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/unique-filename/1.1.1>',
      y18n: 'registry.npmjs.org/y18n/4.0.3'
    },
    depth: 4,
    installable: true,
    resolvedPackage: {
      additionalInfo: [Object],
      depPath: '/cacache/12.0.4',
      dev: false,
      fetchingBundledManifest: [AsyncFunction (anonymous)],
      fetchingFiles: [AsyncFunction (anonymous)],
      filesIndexFile: '/Users/gluxon/Library/pnpm/store/v3/files/6b/4b4c078d2879fbee227af80b06f719eadb2fdc538f50f9ca0d13e71ae31821b27ef6f1b1e2175fb0403bfbbf8485dd69fcce239242df00f01f27f6e1bb8e01-index.json',
      finishing: [AsyncFunction (anonymous)],
      hasBin: false,
      hasBundledDependencies: false,
      id: 'registry.npmjs.org/cacache/12.0.4',
      name: 'cacache',
      optional: false,
      optionalDependencies: Set(0) {},
      patchFile: undefined,
      peerDependencies: {},
      peerDependenciesMeta: undefined,
      prepare: false,
      prod: true,
      requiresBuild: false,
      resolution: [Object],
      version: '12.0.4'
    }
  }
}
```

### Diff
```diff
diff --git a/incorrect.yml b/correct.yml
index 8dfacce..de0234a 100644
--- a/incorrect.yml
+++ b/correct.yml
@@ -2,21 +2,21 @@
   nodeId: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>',
   node: {
     children: {
-      bluebird: 'registry.npmjs.org/bluebird/3.7.2',
-      chownr: 'registry.npmjs.org/chownr/1.1.4',
-      'figgy-pudding': 'registry.npmjs.org/figgy-pudding/3.5.2',
+      bluebird: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/bluebird/3.7.2>',
+      chownr: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/chownr/1.1.4>',
+      'figgy-pudding': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/figgy-pudding/3.5.2>',
       glob: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/glob/7.2.3>',
-      'graceful-fs': 'registry.npmjs.org/graceful-fs/4.2.9',
-      'infer-owner': 'registry.npmjs.org/infer-owner/1.0.4',
+      'graceful-fs': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/graceful-fs/4.2.9>',
+      'infer-owner': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/infer-owner/1.0.4>',
       'lru-cache': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/lru-cache/5.1.1>',
       mississippi: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mississippi/3.0.0>',
       mkdirp: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mkdirp/0.5.5>',
       'move-concurrently': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/move-concurrently/1.0.1>',
-      'promise-inflight': 'registry.npmjs.org/promise-inflight/1.0.1',
+      'promise-inflight': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>',
       rimraf: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/rimraf/2.7.1>',
       ssri: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/ssri/6.0.2>',
       'unique-filename': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/unique-filename/1.1.1>',
-      y18n: 'registry.npmjs.org/y18n/4.0.3'
+      y18n: '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/y18n/4.0.3>'
     },
     depth: 4,
     installable: true,
```

I think the important line is:

```diff
-      'promise-inflight': 'registry.npmjs.org/promise-inflight/1.0.1',
+      'promise-inflight': '>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>',
```

**Comment by gluxon** [comment]
Commenting further debugging notes for myself. The tree node IDs eventually get replaced through a `pathsByNodeId` map id. This maps the internal in-memory tree node IDs the serialized lockfile graph ID.

https://github.com/pnpm/pnpm/blob/761be978b2ed70a5337eaab14e13dab103a6cf93/packages/resolve-dependencies/src/resolvePeers.ts#L95-L100

### Correct (inflight-promise has peer dep)

```js
❯ pathsByNodeId["registry.npmjs.org/promise-inflight/1.0.1"]
"/promise-inflight/1.0.1"

❯ pathsByNodeId[">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>"]
"/promise-inflight/1.0.1_bluebird@3.7.2"
```

### Incorrect (inflight-promise is missing peer dep)

```js
❯ pathsByNodeId["registry.npmjs.org/promise-inflight/1.0.1"]
"/promise-inflight/1.0.1"

❯ pathsByNodeId[">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>"]
undefined
```

## Thoughts

The failing case never visits `cacache/12.0.4>/promise-inflight/1.0.1>` to populate it in `pathsByNodeId`. This makes sense. It's not necessarily the map value that's the problem, but the key we're looking up.

**Comment by gluxon** [comment]
More comments talking to myself.

### What do we know so far?

- When the `bluebird` peer dependency is properly resolved, the dependency tree entry for `/cacache/12.0.4` still has its `children` field undefined. Specifically, it's still set to a function that needs to be called to lazily evaluate it.
- When the `bluebird` peer dependency on `promise-inflight` is improperly missing, the `/cacache/12.0.4` dependency tree entry mysteriously has its `children` already resolved (incorrectly).

### When does `cacache` children get set incorrectly?

I narrowed it down here.

https://github.com/pnpm/pnpm/blob/761be978b2ed70a5337eaab14e13dab103a6cf93/packages/resolve-dependencies/src/resolveDependencies.ts#L496-L500

This sets `ctx.dependenciesTree['>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>'].children` to:

```jsonc
{
    "bluebird": "registry.npmjs.org/bluebird/3.7.2",
    "chownr": "registry.npmjs.org/chownr/1.1.4",
    "figgy-pudding": "registry.npmjs.org/figgy-pudding/3.5.2",
    "glob": ">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/glob/7.2.3>",
    "graceful-fs": "registry.npmjs.org/graceful-fs/4.2.9",
    "infer-owner": "registry.npmjs.org/infer-owner/1.0.4",
    "lru-cache": ">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/lru-cache/5.1.1>",
    "mississippi": ">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mississippi/3.0.0>",
    "mkdirp": ">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/mkdirp/0.5.5>",
    "move-concurrently": ">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/move-concurrently/1.0.1>",
    // 👇 The important line.
    "promise-inflight": "registry.npmjs.org/promise-inflight/1.0.1",
    "rimraf": ">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/rimraf/2.7.1>",
    "ssri": ">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/ssri/6.0.2>",
    "unique-filename": ">packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/unique-filename/1.1.1>",
    "y18n": "registry.npmjs.org/y18n/4.0.3"
}
```

These lines of code never run with the given `parentPkg.nodeId` run in the passing case.

### Also Important

The `resolveCtx` argument here as the `dependenciesTree` that's being mutated above.

https://github.com/pnpm/pnpm/blob/761be978b2ed70a5337eaab14e13dab103a6cf93/packages/resolve-dependencies/src/resolveDependencyTree.ts#L157-L162

Setting a breakpoint right below this line and inspecting the `dependenciesTree` reliably predicts whether the lockfile will flicker or not.

**Comment by gluxon** [comment]
## Queue

Resolving the dependencies tree happens through a queue.

https://github.com/pnpm/pnpm/blob/65c4260dee83486954fc014088e68a89828e4322/packages/resolve-dependencies/src/resolveDependencies.ts#L294

Certain parts of the tree are not added to the queue if they're `!isNew`.

https://github.com/pnpm/pnpm/blob/65c4260dee83486954fc014088e68a89828e4322/packages/resolve-dependencies/src/resolveDependencies.ts#L429-L431

### Visiting `/webpack/4.46.0`.

I was specifically inspecting `>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>`, but whether this path gets visited during the initial dependency tree build depends on whether `/webpack/4.46.0` is visited elsewhere in the tree first.

The `/webpack/4.46.0` dependency appears a few times in the tree.

```
>packages/workspace-2>/@storybook/react/6.4.19>/webpack/4.46.0>`
>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>
>packages/workspace-2>/@storybook/react/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>
>packages/workspace-2>/@storybook/manager-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>
>packages/workspace-2>/@storybook/react/6.4.19>/@storybook/core/6.4.19>/@storybook/core-server/6.4.19>/webpack/4.46.0>
>packages/workspace-2>/@storybook/react/6.4.19>/@storybook/core/6.4.19>/@storybook/core-server/6.4.19>/@storybook/builder-webpack4/6.4.19>/webpack/4.46.0>
>packages/workspace-2>/@storybook/react/6.4.19>/@storybook/core/6.4.19>/@storybook/core-server/6.4.19>/@storybook/manager-webpack4/6.4.19>/webpack/4.46.0>
```

Each of these paths have different lockfile entries for `>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>`, and one of them is setting prioritized for the lockfile.

**Comment by gluxon** [comment]
### nodeId for promise-inflight

This check determines whether `promise-inflight` gets:

- The short `'registry.npmjs.org/promise-inflight/1.0.1`
- The longer `>packages/workspace-2>/@storybook/builder-webpack5/6.4.19>/@storybook/core-common/6.4.19>/webpack/4.46.0>/terser-webpack-plugin/1.4.5>/cacache/12.0.4>/promise-inflight/1.0.1>`.

https://github.com/pnpm/pnpm/blob/4ed825aa49e96e221e0d023de64fc9f4c68b19b6/pkg-manager/resolve-dependencies/src/resolveDependencies.ts#L1232-L1236

### pkgIsLeaf

Here's the definition of `pkgIsLeaf`:

https://github.com/pnpm/pnpm/blob/4ed825aa49e96e221e0d023de64fc9f4c68b19b6/pkg-manager/resolve-dependencies/src/resolveDependencies.ts#L1377-L1381

Here's the value of `pkg` for `promise-inflight`:

```json
{
  "name": "promise-inflight",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
  },
  "version": "1.0.1",
  "peerDependenciesMeta": {
    "bluebird": {
      "optional": true,
    },
  },
}
```

This looks like the culprit. The `promise-inflight` node shouldn't pass `pkgIsLeaf` since it can have a peer dependency. The `pkgIsLeaf` function should likely be checking for `peerDependenciesMeta` too.

## Followup

I'll open a PR tomorrow after testing the updated `pkgIsLeaf` further.

**Comment by gluxon** [comment]
Proposed fix open here https://github.com/pnpm/pnpm/pull/6112

**Comment by apaniel** [comment]
@gluxon I can still reproduce in 7.27.1

**Comment by zkochan** [comment]
It was not released yet.

**Comment by gluxon** [comment]
@apaniel Thanks for working around it. The fix was merged less than a day ago and should be in v7.28 when it's released. Please feel free to reopen this issue if you continue to see unexpected lockfile changes to `promise-inflight` on v7.28.

**Comment by apaniel** [comment]
@gluxon @zkochan my bad, I thought I was looking at the commits of the release, not the commits since the release.
Facepalm ![image](https://user-images.githubusercontent.com/40391767/220197842-ff96d899-6a96-401c-bfd3-d0e3fb5a1bba.jpeg)

**Comment by gluxon** [comment]
No worries! I've made similar mistakes before. 🙂

**Comment by zkochan** [comment]
:ship: v7.28.0-0

**Comment by troch** [comment]
Hello, we've bumped into that issue very recently, and the new version does not fix it (just tried it).

The problem seems to be with duplication of dependencies between workspaces, due to optional peer dependencies. To illustrate, below is an example with `@nestjs/common`:
- It has optional peer dependencies (for example, `class-validator`)
- I have two workspaces using `@nestjs/common`, one which installs `class-validator` and the other one doesn't.

As a result, I have two installs of `@nestjs/common`. But only one install of `@nestjs/core`, which uses `@nestjs/common`. So depending on which workspace I am in, I have a mismatch of `@nestjs/common` (the one used directly in our code, and the one used by `@nestjs/core`). In our case, it causes issues when nest tries to check an error is an instance of `HttpException`.

Although, in the pasted part of our lockfile below, one `@nestjs/common` has `dev: false` and the other not, I confirm they are both installed as `dependencies` and not `devDependencies` (in case this helps).

```
  /@nestjs/common/9.3.9_glt6otmez4zoecyy5ktjxkg6bi:
    resolution: {integrity: sha512-GshTD9Xz+wD2em6NyzU4NXw5IXMUmapgDgD+iuj6XL0258hvDwODmNk37mBBnZvTZlqER+krvIUKnS34etqF/A==}
    peerDependencies:
      cache-manager: <=5
      class-transformer: '*'
      class-validator: '*'
      reflect-metadata: ^0.1.12
      rxjs: ^7.1.0
    peerDependenciesMeta:
      cache-manager:
        optional: true
      class-transformer:
        optional: true
      class-validator:
        optional: true
    dependencies:
      class-validator: 0.13.2
      iterare: 1.2.1
      reflect-metadata: 0.1.13
      rxjs: 7.8.0
      tslib: 2.5.0
      uid: 2.0.1
    dev: false

  /@nestjs/common/9.3.9_mnr6j2del53muneqly5h4y27ai:
    resolution: {integrity: sha512-GshTD9Xz+wD2em6NyzU4NXw5IXMUmapgDgD+iuj6XL0258hvDwODmNk37mBBnZvTZlqER+krvIUKnS34etqF/A==}
    peerDependencies:
      cache-manager: <=5
      class-transformer: '*'
      class-validator: '*'
      reflect-metadata: ^0.1.12
      rxjs: ^7.1.0
    peerDependenciesMeta:
      cache-manager:
        optional: true
      class-transformer:
        optional: true
      class-validator:
        optional: true
    dependencies:
      iterare: 1.2.1
      reflect-metadata: 0.1.13
      rxjs: 7.8.0
      tslib: 2.5.0
      uid: 2.0.1

  /@nestjs/core/9.3.9_q6agyr4hwia55oswpsa7zjxcpm:
    resolution: {integrity: sha512-9g1A1G9eirLXEpH21rc6dKb08zHc2+adhCRz8NW39hbejcsxxD72FApJzt4QBQAKvu862ixt/tdpStnFT7lOSw==}
    requiresBuild: true
    peerDependencies:
      '@nestjs/common': ^9.0.0
      '@nestjs/microservices': ^9.0.0
      '@nestjs/platform-express': ^9.0.0
      '@nestjs/websockets': ^9.0.0
      reflect-metadata: ^0.1.12
      rxjs: ^7.1.0
    peerDependenciesMeta:
      '@nestjs/microservices':
        optional: true
      '@nestjs/platform-express':
        optional: true
      '@nestjs/websockets':
        optional: true
    dependencies:
      '@nestjs/common': 9.3.9_mnr6j2del53muneqly5h4y27ai
      '@nestjs/platform-express': 9.3.9_77foi4w27ghy47yutmnzv7krjy
      '@nuxtjs/opencollective': 0.3.2
      fast-safe-stringify: 2.1.1
      iterare: 1.2.1
      path-to-regexp: 3.2.0
      reflect-metadata: 0.1.13
      rxjs: 7.8.0
      tslib: 2.5.0
      uid: 2.0.1
    transitivePeerDependencies:
      - encoding
 ```
 
 Another example with `@nestjs/graphql`:
 
 ```
 /@nestjs/graphql/10.2.0_5uxocvrwy3keqoc4mv5gfrhdqm:
    resolution: {integrity: sha512-N/sca0eZLJIyyvfusZh1eabGnKBYgQ4LmOCvhI7+oDMiWWK4HOhOEeT5MC11bmd0vq850frWW9qqg+3qRKpiXw==}
    peerDependencies:
      '@apollo/subgraph': ^0.1.5 || ^0.3.0 || ^0.4.0 || ^2.0.0
      '@nestjs/common': ^8.2.3 || ^9.0.0
      '@nestjs/core': ^8.2.3 || ^9.0.0
      class-transformer: '*'
      class-validator: '*'
      graphql: ^15.8.0 || ^16.0.0
      reflect-metadata: ^0.1.13
      ts-morph: ^13.0.2 || ^14.0.0 || ^15.0.0 || ^16.0.0 || ^17.0.0
    peerDependenciesMeta:
      '@apollo/subgraph':
        optional: true
      class-transformer:
        optional: true
      class-validator:
        optional: true
      ts-morph:
        optional: true
    dependencies:
      '@apollo/subgraph': 2.3.2_graphql@16.6.0
      '@graphql-tools/merge': 8.3.18_graphql@16.6.0
      '@graphql-tools/schema': 9.0.16_graphql@16.6.0
      '@graphql-tools/utils': 9.2.1_graphql@16.6.0
      '@nestjs/common': 9.3.9_glt6otmez4zoecyy5ktjxkg6bi
      '@nestjs/core': 9.3.9_q6agyr4hwia55oswpsa7zjxcpm
      '@nestjs/mapped-types': 1.2.2_usol472mskniycdkgert4kncae
      chokidar: 3.5.3
      class-validator: 0.13.2
      fast-glob: 3.2.12
      graphql: 16.6.0
      graphql-tag: 2.12.6_graphql@16.6.0
      graphql-ws: 5.11.3_graphql@16.6.0
      lodash: 4.17.21
      normalize-path: 3.0.0
      reflect-metadata: 0.1.13
      subscriptions-transport-ws: 0.11.0_graphql@16.6.0
      ts-morph: 17.0.1
      tslib: 2.5.0
      uuid: 9.0.0
      ws: 8.12.0
    transitivePeerDependencies:
      - bufferutil
      - utf-8-validate
    dev: false

  /@nestjs/graphql/10.2.0_kctxk6zqs6hekhubp3nz5igkbq:
    resolution: {integrity: sha512-N/sca0eZLJIyyvfusZh1eabGnKBYgQ4LmOCvhI7+oDMiWWK4HOhOEeT5MC11bmd0vq850frWW9qqg+3qRKpiXw==}
    peerDependencies:
      '@apollo/subgraph': ^0.1.5 || ^0.3.0 || ^0.4.0 || ^2.0.0
      '@nestjs/common': ^8.2.3 || ^9.0.0
      '@nestjs/core': ^8.2.3 || ^9.0.0
      class-transformer: '*'
      class-validator: '*'
      graphql: ^15.8.0 || ^16.0.0
      reflect-metadata: ^0.1.13
      ts-morph: ^13.0.2 || ^14.0.0 || ^15.0.0 || ^16.0.0 || ^17.0.0
    peerDependenciesMeta:
      '@apollo/subgraph':
        optional: true
      class-transformer:
        optional: true
      class-validator:
        optional: true
      ts-morph:
        optional: true
    dependencies:
      '@graphql-tools/merge': 8.3.18_graphql@16.6.0
      '@graphql-tools/schema': 9.0.16_graphql@16.6.0
      '@graphql-tools/utils': 9.2.1_graphql@16.6.0
      '@nestjs/common': 9.3.9_mnr6j2del53muneqly5h4y27ai
      '@nestjs/core': 9.3.9_q6agyr4hwia55oswpsa7zjxcpm
      '@nestjs/mapped-types': 1.2.2_ilxajbd2e536h4oohar7aljlry
      chokidar: 3.5.3
      fast-glob: 3.2.12
      graphql: 16.6.0
      graphql-tag: 2.12.6_graphql@16.6.0
      graphql-ws: 5.11.3_graphql@16.6.0
      lodash: 4.17.21
      normalize-path: 3.0.0
      reflect-metadata: 0.1.13
      subscriptions-transport-ws: 0.11.0_graphql@16.6.0
      ts-morph: 17.0.1
      tslib: 2.5.0
      uuid: 9.0.0
      ws: 8.12.0
    transitivePeerDependencies:
      - bufferutil
      - utf-8-validate
    dev: false
```

**Comment by apaniel** [comment]
I think that is a different issue @troch, but is one that I also have.
I'm trying to create a smaller repo to reproduce it (I cannot share the company repo where the issue is) but I haven't been able to reproduce it in a smaller scale. Is this repo something you can share @troch?

**Comment by troch** [comment]
I'm not able to share @apaniel

**Comment by apaniel** [comment]
@troch maybe you have better luck than me trying to create a small repo to reproduce :D

**Comment by gluxon** [comment]
Hi @troch — As frustrating as it is, it is expected that there are two copies of `@nestjs/common` in the example mentioned. To maintain dependency strictness, pnpm intentionally "boxes" dependencies with peer dependencies into a folder where they're only able to `require`/`import` peer dependencies (optional or required) visible to it. See https://pnpm.io/how-peers-are-resolved for details.

For your specific example, adding `class-validator` to `devDependencies` in your other workspace should make pnpm install only one copy of `@nestjs/common`.

That said, I've found this personally surprising as well and not satisfied with the `devDependencies` workaround. I have some ideas in this area that I'll post to a separate discussion soon. Will update this issue with a link when I've done that.

**Comment by troch** [comment]
@gluxon thanks for your reply. I understand the idea of "boxing" dependencies. That said, it is problematic in cases like that where the "boxing" is limited to the dependency itself (with the error described), and not performed at a workspace-level / isolation between workspaces (or at least the part which needs it). If `@nestjs/common` is duplicated, a possible approach would be for parent dependencies consuming it to be duplicated as well, and so on...

A workaround I'm trying just now, tell me if you see something wrong with it: to install dev dependencies at the root and use the option `resolve-peers-from-workspace-root=true`. It seems to deduplicate, and a bit less intensive than going through each workspace individually.

**Comment by gluxon** [comment]
@troch The `resolve-peers-from-workspace-root` workaround was what I'm using too.

@zkochan just put up an awesome new feature as well. https://github.com/pnpm/pnpm/pull/6153

When the new `dedupe-peer-dependencies` option is available, I think it'll prevent the problem you're describing without adding dependencies to the root `package.json`.
