### ISSUE TITLE
Concurrent calls to `pnpm` `link` or `install` often error out on Windows (EPERM, ENOENT)

### ISSUE THREAD

**Issue by 0liver** [pnpm/pnpm#5672]
### pnpm version:
7.17.0

### Code to reproduce the issue:

Needs to be run on Windows.

#### Powershell

```pwsh
# Create a new folder and enter it.
mkdir pnpm-install-error-repro && cd pnpm-install-error-repro
# Fetch the package.json we're using.
Invoke-WebRequest https://raw.githubusercontent.com/Lombiq/NodeJs-Extensions/issue/OSOE-84-final/Lombiq.NodeJs.Extensions/package.json -OutFile package.json
# Run 10 concurrent installation jobs.
1..10 | ForEach-Object -Parallel { mkdir -force $_; cd $_; cp ..\package.json . ; pnpm i --prod --prefer-offline;  } -ThrottleLimit 10
```

### Expected behavior:
Runs as flawlessly and error-free as on Ubuntu.

### Actual behavior:
Fails most of the time with 1 or more errors along the [lines of](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3518291946/jobs/5897041492#step:6:315):

> EPERM: operation not permitted, open 'C:\Users\runneradmin\AppData\Local\pnpm\store\v3\files\71\3d2cf4f944987618f4e82eff7cee4bec8e5e0af4f1de8eaa0bcd75cdfea33484c4cb19d19033b9384bf93b4086476aaa0b467394d423fb5b9ee83e88c9daa5'

[Or this:](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3517849399/jobs/5896839277#step:6:294)

> ENOENT: no such file or directory, copyfile 'C:\Users\runneradmin\AppData\Local\pnpm\store\v3\files\04\d1b45ab12c3268a41cf1f9c0c5b80f613ad10e6fc75665bd22b07856274e8d3e9c6023684d8498d84244f7a862edb101b8f8c5dfa2d3bcb536c0a41b4805ba' -> 'C:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\src\Modules\Lombiq.Privacy\Lombiq.Privacy\node_modules\.nx\node_modules\.pnpm\caniuse-lite@1.0.30001434\node_modules\_tmp_2932_cbd10cae3db5e375306c43dff77ca80a\data\features\link-rel-preload.js'

### Additional information:

 - `node -v` prints: **v16.17.0**
 - Windows, macOS, or Linux?: **Windows 10**

**Comment by Lionad-Morotar** [comment]
I had this error too, and solved by delete .pnpm-store

**Comment by 0liver** [comment]
Thanks for sharing. I'll give it a try.

**Comment by 0liver** [comment]
First off, I wanted to comment on this:

> I had this error too, and solved by delete .pnpm-store

I'm not exactly sure how deleting **.pnpm-store** fixes this, but it is not a feasible solution for us since it would incur the penalty of re-downloading all of the needed packages.

With that out of the way, I'm stuck with, what it seems, concurrency issues.

### Here's our situation

1. We use `pnpm install` to install an npm package from the file system to a central folder, and then `pnpm link` that installation into a project/folder.
2. We do the linking in parallel in around 10 projects. (This is a .NET environment, so they are all part of a solution which we build with `dotnet build`.)
3. Seemingly randomly, we see the following errors when executing `pnpm link C:\Projects\Lombiq\OSOCE\node_modules\.nx`:
    ```
    ENOENT: no such file or directory, unlink 'C:\Projects\Lombiq\OSOCE\node_modules\.nx\node_modules\.pnpm\node_modules\functions-have-names'
    ```
    The concrete npm package varies wildly, and also the number of failures. Currently, we simply repeat the `pnpm link` call after a failure (up to 2x) but that's still fragile, and also slows down the whole build due to some random backoff time in between the invocations.
4. When I check the existence of the file system entry mentioned in above error, it's actually always there.

I am puzzled by the fact that `pnpm link` invokes `unlink`, but I obviously know too little about pnpm.

Could anyone shed some light on this?

**Comment by kihlaj** [comment]
I am having the same issue, but with web3 projects. Deleting C:\Users\{username}\AppData\Local\pnpm\store\v3 solves the problem, but I have to do it everytime for every web3 project I have to deal with. I didn't try with too many projects. Without web3 packages involved, it is fine. I don't get this error.

**Comment by 0liver** [comment]
UPDATE: We've gone to great length working around this problem by serializing the `pnpm link` calls from all our projects using a [mutex](https://github.com/Lombiq/NodeJs-Extensions/blob/dev/Lombiq.NodeJs.Extensions/ExecWithMutex.cs). This works for now.

But we still receive intermittent errors when running `pnpm build` in the same projects. These executions take around 20s on our build server (GitHub Actions), so serializing them would incur a huge performance penalty.

The interesting bit is that only 1 in 14 projects fails, although most of them run the exact same script. I suspect that there is still some interference happening between a `pnpm link` call from one project and a `pnpm build` call from another project.

What exactly does `pnpm link` do on the file system? It seems to alter the `source` directory of the link operation, which in our case is a kind of shared folder. Is that correct? Can you point me to more details?
