### ISSUE TITLE
`pnpm install --filter` (to install dependencies only for selected workspace projects) not working with `dedupe-peer-dependents` set to `true`

### ISSUE THREAD

**Issue by pkerschbaum** [pnpm/pnpm#6300]
### pnpm version:

- problem present in 8.0.0 with `dedupe-peer-dependents` not set (thus `true` = default value of v8.0.0)
- problem not present in 8.0.0 with `dedupe-peer-dependents` set to `false`

### Code to reproduce the issue:
https://github.com/pkerschbaum/pnpm-issue-workspaces-no-filter-applied-for-install

### Expected behavior:

`pnpm install --filter "package-a"` should only install dependencies of workspace project `package-a`.

### Actual behavior:

It installs all dependencies.  
I tried to also clean the pnpm store before (`rm -rf $(pnpm store path)`) because I thought maybe pnpm installs more dependencies when they are on the machine already in the store, but even then all dependencies get downloaded&installed.

![image](https://user-images.githubusercontent.com/13141109/228199597-47bf5e15-9e6e-48fc-811e-da61c3aa0fde.png)

### Additional information:

 - `node -v` prints: v16.19.0
 - Windows, macOS, or Linux?: Ubuntu 22.04.1 LTS

**Comment by elclanrs** [comment]
I'm experiencing this bug too. I noticed when I tried to install only root workspace dependencies and it begun installing all dependencies. I also tried clearing node_modules, pnpm store, etc.

```sh
pnpm i -w # installs all dependencies in 8.0.0
```

**Comment by zkochan** [comment]
This is probably happening because this setting is true by default: https://pnpm.io/npmrc#dedupe-peer-dependents

**Comment by jazmon** [comment]
Couldn't the deduping only be applied to what is being installed with the `--filter`? In our case this setting causes our monorepo install time in the CI to go from 55 seconds to nearly 7 minutes.

**Comment by pkerschbaum** [comment]
@zkochan oh right - when I set that setting to false by running `pnpm config --location=project set dedupe-peer-dependents=false`, the dependencies filter is applied again correctly!  
Consequently, this issue might have the same cause as #6264.

Will update issue title and description accordingly...

**Comment by sawden** [comment]
I am also facing this issue with pnpm@7.32.2.

**Comment by faradaytrs** [comment]
yeah it's still a problem

**Comment by AdriVanHoudt** [comment]
It seems like `pnpm i --filter=xxx --dedupe-peer-dependents=false` fixes the issue indeed.
Would be nice to maybe mention in the docs that this (default) setting "breaks" (depending on how you look at it :P) some expected filters.

**Comment by mm-edtake** [comment]
Thanks @nnhjs 
I'll wait for this issue to be fixed.
I have options to deal we that so it's ok from my side.

I delete pnpm-lock file before building this specific app so i can then cp all {root}/node_modules to the app bundle (issue #6259)

**Comment by verekia** [comment]
As a dirty workaround, you can delete folders of unwanted packages before installing.
It's not too bad in a simple monorepo where you have client/server/shared code, for instance.
I delete the server folder before the client install, and I delete the client folder before the server install.

**Comment by michaelkplai** [comment]
I've also noticed that setting `node-linker=hoisted` also installs all dependencies even when `dedupe-peer-dependents` is set to `false`.

**Comment by osdiab** [comment]
i'm finding on pnpm 8.7.0 `pnpm i --filter=xxx --dedupe-peer-dependents=false` doesn't work with this error:

```
ERROR  Unknown option: 'dedupe-peer-dependents'
Did you mean 'strict-peer-dependencies'? Use "--config.unknown=value" to force an unknown option.
For help, run: pnpm help install
```

Was this flag removed?

**Comment by ka2n** [comment]
@osdiab FYI `--config.dedupe-peer-dependents=false` would work as same effect.

**Comment by osdiab** [comment]
Thanks for that - it does work then, but yeah due to aforementioned issues from other commenters it doesn't help in CI. Eagerly awaiting this to be resolved, as installs are using up a lot of CI time and therefore costing my company real dollars.

**Comment by WhiteKiwi** [comment]
The pnpm filter does not work too if other options such as injected are turned on, other than depute-peer-dependent

**Comment by khokm** [comment]
`pnpm -F <project> --config.dedupe-peer-dependents=false i` works fine if projects only depends on packages from NPM registry.
If project depends on local packages (i.e. `workspace:` protocol), it also works.
BUT! If local packages also have dependencies (local or from NPM), they will not be installed.
I.e. package `@local/backend` depends on `@local/client`, which depends on `axios`. `axios` is not installing, build failed.

**Comment by schmod** [comment]
Do we actually understand the root-cause of this issue?

**Comment by urbanisierung** [comment]
> BUT! If local packages also have dependencies (local or from NPM), they will not be installed.

@khokm what's your approach for this issue? Installing dependencies of local packages manually?

**Comment by khokm** [comment]
@urbanisierung i'm just appending an [ellipsis](https://pnpm.io/filtering#--filter-package_name-1) i.e. `pnpm--filter package-a... i`. This installs `package-a` direct and indirect dependencies and root dependencies also. 

Currently I also can't reproduce this issue with `pnpm` 8.15.4. `pnpm -F package-a` install only `package-a` deps + root; appending an ellipsis installs inderect deps also - as it should be.

**Comment by mark-omarov** [comment]
It's complex and I lack proper understanding but let me try.

The deduplication process requires resolving a full dependency graph. This graph ensures that all relevant peer dependencies are considered for deduplication. However, this approach causes to include all packages, even those that are not immediately relevant to the selected projects when `--workspace-root` and/or `--filter` specified.

My initial thought was to only consider the graph related to the filtered projects (`selectedProjectsGraph` or filtered `allProjectsGraph` after `opts.allProjectsGraph ?? createPkgGraph(allProjects, {  linkWorkspacePackages: Boolean(opts.linkWorkspacePackages), }).graph` based on `selectedProjectsGraph` entries). 
        
https://github.com/pnpm/pnpm/blob/fd6cd2781716dd6c020474beae2f3a3da8493e6b/pkg-manager/plugin-commands-installation/src/installDeps.ts#L174-L187

While it probably reduces the set of packages being analyzed and deduplicated, it might have implications that I'm not able to realize yet. But, I could think of some possibilities:
- Installing dependencies only for a subset of projects might break the deduplication consistency since the whole dependency graph isn't know.
- Subsequent installations for other workspace projects (filtered) or the entire workspace could lead to inconsistencies or duplication issues.

I think this requires further investigation. It would be great if @zkochan or @gluxon could look into it. Thanks!

**Comment by clayrisser** [comment]
This is not a viable alternative for yarn until the equivalent of `yarn workspaces focus` is supported while having `node-linker=hoisted` set.

https://yarnpkg.com/cli/workspaces/focus

**Comment by clayrisser** [comment]
I need to prune the dependencies from from packages that are not related to my current build to keep my docker image small. Right now I have to either delete the folders as @verekia suggested or remove the workspace from the `pnpm-workspaces.yaml`. Either way, it completely recalculates which means I do not benefit from the lockfile.

Quite the delima.

**Comment by zkochan** [comment]
These issues should be solved if we do this change: https://github.com/pnpm/pnpm/issues/8165

**Comment by zkochan** [comment]
Try v9.4.0

**Comment by zkochan** [comment]
> I need to prune the dependencies from from packages that are not related to my current build to keep my docker image small.

There is a special command for preparing a package for docker: [pnpm deploy](https://pnpm.io/cli/deploy).

**Comment by clayrisser** [comment]
Yes, except that pnpm deploy doesn't work when `node-linker=hoisted`.

https://github.com/pnpm/pnpm/issues/6682

**Comment by damianobarbati** [comment]
I still see this issue, I'm trying to install the dependencies of only 1 folder but everything is installed:
```sh
$ pnpm config list
engine-strict=true
registry=https://registry.npmjs.org/
user-agent=pnpm/9.1.0 npm/? node/v22.1.0 darwin x64

$ pnpm -F api install --prod --frozen-lockfile
```

Inspecting node_modules/.pnpm I can see packages from all other services installed.
In fact:
```sh
```

**Comment by zkochan** [comment]
:ship: [9.5.0-beta.3](https://github.com/pnpm/pnpm/releases/tag/v9.5.0-beta.3)

**Comment by clayrisser** [comment]
@bdoof what is your `.nvmrc` settings?
