### ISSUE TITLE
"ERR_INVALID_THIS" on "pnpm up" in Node 20

### ISSUE THREAD

**Issue by jakebailey** [pnpm/pnpm#6424]
### Code to reproduce the issue:

In a pnpm project, install, then run `pnpm up`.

An easy repro is just to try it in the pnpm repo itself.

### Expected behavior:

No error

### Actual behavior:

```
 WARN  GET https://registry.npmjs.org/@definitelytyped%2Fdefinitions-parser error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@definitelytyped%2Fdtslint-runner error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@definitelytyped%2Fheader-parser error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@definitelytyped%2Ftypescript-versions error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@definitelytyped%2Futils error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/typescript error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@definitelytyped%2Fdtslint error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@octokit%2Fcore error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@octokit%2Frest error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/comment-json error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/d3-array error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/d3-axis error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/d3-scale error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/d3-selection error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/d3-time error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/d3-time-format error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
```

### Additional information:

 - `node -v` prints: v20.0.0
 - Windows, macOS, or Linux?: Linux

**Comment by jakebailey** [comment]
There are other issues like this, it seems:

```
pnpm install
Scope: all 142 workspace projects
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/pnpm: Value of "this" must be of type URLSearchParams
Lockfile is up to date, resolution step is skipped
```

**Comment by jakebailey** [comment]
The original issue seems to be thrown by `node-fetch`. I think that updating node-fetch should work?

**Comment by anurag-roy** [comment]
I updated to node v20 last night using
```
pnpm env use --global 20
```
and faced similar issues but the problem is now I cannot even go back to node v19 or v18
```
pnpm env use --global 19
 WARN  GET https://nodejs.org/download/release/index.json error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
```

**Comment by KingBael09** [comment]
In my case pnpm works fine with previous node version (v19.8.1). 

only when I try to use node v20, it throws  ` (ERR_INVALID_THIS) `

```
 WARN  GET https://registry.npmjs.org/create-t3-app error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
```

**Comment by JouanDeag** [comment]
Can confirm this only seems to happen on the latest node 20 and using a previous version (19.9.0 in my case) it works fine.

Getting: `ERR_INVALID_THIS` as well as:
` ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/packagename: Value of "this" must be of type URLSearchParams`

**Comment by gipo355** [comment]
Confirm, same problem on updating to node 20 with asdf and pnpm 8.3.0

Stack trace on running `pnpm install -r`: 
```
 WARN  GET https://registry.npmjs.org/@nrwl/eslint-plugin-nx/-/eslint-plugin-nx-15.9.2.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_INVALID_THIS  Value of "this" must be of type URLSearchParams

pnpm [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at new NodeError (node:internal/errors:399:5)
    at Proxy.getAll (node:internal/url:482:13)
    at Proxy.<anonymous> (/home/wol/.cache/node/corepack/pnpm/8.3.0/dist/pnpm.cjs:60672:55)
    at /home/wol/.cache/node/corepack/pnpm/8.3.0/dist/pnpm.cjs:60734:31
    at Array.reduce (<anonymous>)
    at Proxy.raw (/home/wol/.cache/node/corepack/pnpm/8.3.0/dist/pnpm.cjs:60733:33)
    at new Headers (/home/wol/.cache/node/corepack/pnpm/8.3.0/dist/pnpm.cjs:60618:28)
    at getNodeRequestOptions (/home/wol/.cache/node/corepack/pnpm/8.3.0/dist/pnpm.cjs:60967:23)
    at /home/wol/.cache/node/corepack/pnpm/8.3.0/dist/pnpm.cjs:61024:25
    at new Promise (<anonymous>)
```

when reverting to node 19 with asdf and pnpm 8.1 no problems occur

**Comment by zkochan** [comment]
We'll switch to a fork of node-fetch with a fix. Here's the fix: https://github.com/pnpm/node-fetch/pull/1

**Comment by zkochan** [comment]
Fixed in v8.3.1

**Comment by ekwoka** [comment]
To help anyone else using pnpm globally installed by pnpm:

```js
npx pnpm i -g pnpm@latest
```

**Comment by marifcelik** [comment]
> We'll switch to a fork of node-fetch with a fix. Here's the fix: [pnpm/node-fetch#1](https://github.com/pnpm/node-fetch/pull/1)

hi, why don't you use native 'fetch'? So wouldn't you be avoiding problems like this in the future?

**Comment by rfilgas** [comment]
This doesn't appear to be fully fixed unless I'm missing something- I''m running on a Mac and have updated to the latest but it still persists.

**Comment by zkochan** [comment]
> hi, why don't you use native 'fetch'? So wouldn't you be avoiding problems like this in the future?

native fetch is not present in node.js v16. And even in node.js v18 it is experimental. So, we cannot use it.

**Comment by ekwoka** [comment]
> native fetch is not present in node.js v16. And even in node.js v18 it is experimental. So, we cannot use it.

On 18 it's not behind a flag, at least.

So we can make that PR in September when 16 is EOL?

**Comment by zkochan** [comment]
It would be a breaking change. I don't know when the next major will be released.

**Comment by ar4hc** [comment]
`corepack prepare pnpm@8.3.1 --activate`
did the trick for me, on mac.

pnpm was installed with the node/corepack brew package so i didn't want to use npx as mentioned above (https://github.com/pnpm/pnpm/issues/6424#issuecomment-1515748464).

**Comment by sannajammeh** [comment]
I'm still getting this error when deploying to my Render.com instance with Node 20 enabled. 

Even using corepack does not solve the issue.

**Comment by Nightvision53** [comment]
I have same issue as well on WSL 2. I'm trying to install turborepo starter but it cant install dependences.
![image](https://github.com/pnpm/pnpm/assets/62076627/6daf7240-cae3-4ea2-96cb-bf49b3fe03c4)

**Comment by Nightvision53** [comment]
For those who have the same problem just revert your node installation to v18.17.0

**Comment by jakebailey** [comment]
The logs show that you're running pnpm 7.15, which is much too old for this issue to have been fixed. You need to upgrade to at least 7.32.2 or 8.3.1.

**Comment by Nightvision53** [comment]
> The logs show that you're running pnpm 7.15, which is much too old for this issue to have been fixed. You need to upgrade to at least 7.32.2 or 8.3.1.

I was using latest then and it doesn't work either. Logs show that version because I tried running commands from the people above to solve my problem and neither of them worked. 

[#52955](https://github.com/vercel/next.js/pull/52955) I came across this and it just says don't use node 20. SO when I reverted to LTS version of Node it solved.

**Comment by jakebailey** [comment]
That cross-linked issue mentions `PNPM 7.24.3`, which is still too old. If you have logs that show this happening with the latest versions of pnpm, then it'd be great to provide them.

**Comment by Nightvision53** [comment]
Now I changed my Node version to 20 and it worked. But when I look back to my terminal I can see I got this issue on `PNPM 
 8.3.1` when I use it for the first time.
![image](https://github.com/pnpm/pnpm/assets/62076627/e121bdf5-e2df-4506-9cef-c2da11ebd528)

**Comment by jakebailey** [comment]
That corepack command doesn't do anything if you have `packageManager` set in your `package.json`: 

![image](https://github.com/pnpm/pnpm/assets/5341706/6a669baa-87bc-4649-8de2-bcff41fc2043)

You need to bump your `package.json` to be newer.

**Comment by Nightvision53** [comment]
Yes, you are right I have `"packageManager": "pnpm@7.15.0",` on my `package.json`. It came default with the starter of turborepo. 
![image](https://github.com/pnpm/pnpm/assets/62076627/7b4c1260-c0fe-4e84-a934-9e2eb716eace)

**Comment by neerajkumar161** [comment]
> 8.3.1

By updating PNPM version to ```v8``` worked for me. Thank you so much :rocket:

**Comment by itwondersteam** [comment]
switch to node v18 lts works fine. Error with v20.5.0

```
nvm install v18.17.1
pnpm add vue-tippy@v6
```

**Comment by samson-sham** [comment]
> To help anyone else using pnpm globally installed by pnpm:
> 
> ```js
> npx pnpm i -g pnpm@latest
> ```

` ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/pnpm: Value of "this" must be of type URLSearchParams`
Is it just me?

**Comment by sannajammeh** [comment]
> > To help anyone else using pnpm globally installed by pnpm:
> > ```js
> > npx pnpm i -g pnpm@latest
> > ```
> 
> ` ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/pnpm: Value of "this" must be of type URLSearchParams` Is it just me?

Its probably executing pnpm from cache causing the same issue. `npx pnpm@latest i -g pnpm@latest` should do the trick. Or just install `npm i -g pnpm@latest` directly.

**Comment by eduardklinger** [comment]
Very strange... in my case nothing worked for me until I used:

`yarn global add pnpm@latest`

**Comment by giuseppe-g-gelardi** [comment]
hi, sorry if this isn't helpful but i just went through having this issue. not sure how it happened but pnpm home/path wasn't properly added to my .zshrc. once i added it and sourced the file, everything worked. so if you're still having issues, give that a try. again, i apologize if this isn't the most helpful, this is just what worked for me.

**Comment by ekwoka** [comment]
This issue does happen inside github actions when using act to run them locally. Annoying...

even with standalone script installation via the action

**Comment by ekwoka** [comment]
Yes, as above, if I use an older version, and use .npmrc to define a newer node version, then it works fine, but you may not actually want to use an npmrc to control node versions

**Comment by jakebailey** [comment]
The stack trace shows that you're still using 8.1.1, and the fix for this was only introduced in 8.3.1.

See: https://github.com/mswjs/cookies/actions/runs/6798894268/job/18483965198?pr=29#step:4:18

This is because your workflow says `version: 8.10`, which YAML reads as being the same value as `8.1` as it's parsed as a number.

**Comment by ekwoka** [comment]
Specifically, the issue is that the action v2 does not point to the newest version. The tags are mostly messed up, so you'd want to use actions v2.4

**Comment by Nightvision53** [comment]
This issue happens a lot. I think you guys need to point somewhere in the docs that pnpm automaticly uses the version specified in package.json.

**Comment by jakebailey** [comment]
> Specifically, the issue is that the action v2 does not point to the newest version. The tags are mostly messed up, so you'd want to use actions v2.4

There is nothing wrong with `pnpm/action-setup`; looking at a recent GHA run in one of my projects, v2 pointed to `d882d12c64e032187b2edb46d3a0d003b7a43598` which is https://github.com/pnpm/action-setup/releases/tag/v2.4.0. The above issue is due to `3.10` being parsed as a number and not a string.

> This issue happens a lot. I think you guys need to point somewhere in the docs that pnpm automaticly uses the version specified in package.json.

The readme of the action (https://github.com/pnpm/action-setup#version) says:

> Optional when there is a packageManager field in the package.json.

Are you referring to the action docs or is there some other doc that should also say this?

**Comment by ekwoka** [comment]
> There is nothing wrong with pnpm/action-setup; looking at a recent GHA run in one of my projects, v2 pointed to d882d12c64e032187b2edb46d3a0d003b7a43598 which is https://github.com/pnpm/action-setup/releases/tag/v2.4.0. The above issue is due to 8.10 being parsed as a number and not a string.

https://github.com/pnpm/action-setup/tags

bit strange since that's not where the tags point to.

**Comment by Nightvision53** [comment]
> Are you referring to the action docs or is there some other doc that should also say this?

I am referring to [pnpm](https://github.com/pnpm/pnpm) docs not the action docs. Because this misunderstanding not just happens in github actions. I also experienced it on my local environment. Just put some kind of warning that pnpm will use the version on the package.json not the one that you have on your device. (If something like that already exist, you can ignore my comment)

**Comment by jakebailey** [comment]
`v2` is a branch: https://github.com/pnpm/action-setup/tree/v2

**Comment by ekwoka** [comment]
Ah, that would explain that.

That some versions are tagged and some are branches....

**Comment by acidjazz** [comment]
This should definitely not be closed

**Comment by Tommoore96** [comment]
I get it when using `pnpm install` on node version 21 and I'm using pnpm version 8.8.0.

```
 WARN  GET https://registry.npmjs.org/@radix-ui%2Freact-icons error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@radix-ui%2Freact-radio-group error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
| Progress: resolved 0, reused 1, downl../..                                    
| Progress: resolved 23, reused 23, dow../..                                    
| Progress: resolved 29, reused 29, dow../..
| Progress: resolved 30, reused 30, dow WARN  GET https://registry.npmjs.org/@radix-ui%2Freact-icons error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
| Progress: resolved 30, reused 30, dow WARN  GET https://registry.npmjs.org/@radix-ui%2Freact-radio-group error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
| Progress: resolved 30, reused 30, downloaded 0, added 0
```

**Comment by zkochan** [comment]
> This should definitely not be closed

How so? When this issue was opened, our CI was failing with the specified error (we have lots of e2e tests making requests to the registry). Right now the CI is passing with both Node.js 20 and 21.

**Comment by welschmoor** [comment]
To me a newer version of pnpm helped. I had to install it using `npm install -g pnpm --force` if I recall correctly.

**Comment by usrrname** [comment]
I'm finding this issue on Apple M2 Pro while using [nektos/act](https://github.com/nektos/act) with pnpm 8.10.0 and node v20.9.0

**Comment by pisharodySrikanth** [comment]
Still happening for me with pnpm v8.14.0 and node v20.10.0

**Comment by adamponddesign** [comment]
I'm on a mac M1, using corepack (node v20.10.0, pnpm v8.14.1) and the following rectified the issue for me
`corepack prepare pnpm@latest --activate`

Hope it helps someone.

**Comment by ammar-oker** [comment]
I'm still facing this issue with pnpm@8.14.2 and Node@20, it worked fine after downgrading to Node@18.

**Comment by jakebailey** [comment]
This bug is most certainly fixed. You should verify that you're actually using that pnpm version and that something is not being overridden in your environment, e.g. by corepack or similar.

**Comment by ammar-oker** [comment]
@jakebailey yes, you're correct. it was getting overridden by corepack :)

**Comment by doowb** [comment]
> This bug is most certainly fixed. You should verify that you're actually using that pnpm version and that something is not being overridden in your environment, e.g. by corepack or similar.

FWIW, as a first time user of `pnpm`, I experienced this issue and believe it's still an unfixed bug.

I followed a link to the [pnpm installation page](https://pnpm.io/installation) to install `pnpm`.
The first few lines of the installation page do not make it clear that using the standalone script is the preferred way to install `pnpm`. I read those lines as saying that I "could" use the standalone script if I'm on an older version of Node.js, however, I can use native Node.js features like `corepack` or `npm` to install `pnpm`.

I choose to use `corepack` since all I had to do was this:

```
corepack enable pnpm
```

Then I run `pnpm i` in the project that I'm attempting to set up and I get the `ERR_INVALID_THIS` over and over.

I find this issue and check my `pnpm` version and see that `corepack` has installed an old version by default, so I followed instructions to update the version. After updating the version of `pnpm`, I continued to get the same `ERR_INVALID_THIS`. I switched to `node v18.18.0` and the issue went away.

I switched back to `node v21.6.0`, "disabled" pnpm by running `corepack disable pnpm`, then installed `pnpm` using the standalone script.

Since at one point, I used corepack to update pnpm to the latest, and that didn't work, I consider this to still be a bug.

Of course, now that I got to a point where `pnpm i` works, I'm running into another issue that I believe may be a core Node.js issue detecting the cpu arch since `pnpm` seems to have installed the correct optional dependency (`@rollup/rollup-darwin-arm64`), but the library (`rollup`) thinks it should be `@rollup/rollup-darwin-x64`.

**Comment by simlmx** [comment]
Don't forget to update the version in your `package.json` if it was set!

`
"packageManager": "pnpm@8.3.1"
`

**Comment by Bessonov** [comment]
You can use `corepack up` to update your pnpm version **and** `packageManager` in `package.json` in one step.

**Comment by ekwoka** [comment]
This is still happening specifically when using act using node 20, either with an image with node20 or using node setup action before pnpm.

I know ACT isn't necessarily something pnpm has reason to specially investigate, but it seems something about docker, node20 and pnpm is an issue.

This is the case with the 9 alpha as well.

What I've mostly done is use node18 images, and have pnpm manage and use node20, but it's extremely strange.

Not even sure where an investigation would start, but just want whomever to know that this is an issue that exists, even if outside the scope of PNPM to resolve.

**Comment by Lenvia** [comment]
Still happening, with pnpm v8.15.3 and node v20.11.0

**Comment by ryne-sunrun** [comment]
> You can use `corepack up` to update your pnpm version **and** `packageManager` in `package.json` in one step.

This fixed it for me! Thanks

**Comment by jercomio** [comment]
Hi,
I use Node v20 and I tried to use `corepack up` to update my pnpm version and `packageManager` in `package.json `. But it doesn't work for me, I've a same error.

**Comment by waldi** [comment]
My problem was that I was using the pnpm provided via homebrew.

Check via:

```
which pnpm
```

If it is `/opt/homebrew/bin/pnpm` uninstall via `brew uninstall pnpm` and install via `npx pnpm i -g pnpm@latest`

**Comment by jercomio** [comment]
> which pnpm

No, for me it's `/usr/local/bin/pnpm`

**Comment by stub4ever** [comment]
> Don't forget to update the version in your `package.json` if it was set!
> 
> `"packageManager": "pnpm@8.3.1"`

This was the solutions for me updated the packagesManager into "pnpm@8.3.1"

**Comment by mxdlzg** [comment]
Still happen with pnpm 9.0.6 and node v20.11.1

**Comment by shubhank-saxena** [comment]
> My problem was that I was using the pnpm provided via homebrew.
> 
> Check via:
> 
> ```
> which pnpm
> ```
> 
> If it is `/opt/homebrew/bin/pnpm` uninstall via `brew uninstall pnpm` and install via `npx pnpm i -g pnpm@latest`

This worked out for me! Thanks

**Comment by ethanMacNamara** [comment]
this is still happening

**Comment by charanjit-singh** [comment]
Restarting terminal fixed the issue

**Comment by johnstew** [comment]
Seeing this in a CLI environment after zero changes between yesterday and today. 

<img width="920" alt="Screenshot 2024-07-03 at 8 18 04 PM" src="https://github.com/pnpm/pnpm/assets/2146973/0858bb17-fc2e-4e62-a491-ed582fc70d3a">

**Comment by haloboy777** [comment]
I'm also facing this issue.
<img width="988" alt="Screenshot 2024-07-04 at 06 00 11" src="https://github.com/pnpm/pnpm/assets/11489832/7ce7d861-2be5-437f-bef6-416d27cc370e">

**Comment by johnstew** [comment]
I was able to fix this by bumping the action and the pnpm version

<img width="883" alt="Screenshot 2024-07-03 at 8 44 08 PM" src="https://github.com/pnpm/pnpm/assets/2146973/12bd4172-3e3d-44f2-abfa-440429eff92f">

**Comment by r-guerin0** [comment]
Still happening using v9.4

<img width="879" alt="Screenshot 2024-07-04 at 09 44 27" src="https://github.com/pnpm/pnpm/assets/108666643/0814f8c6-99cd-46e9-9ae9-117dc3cf4e8a">

**Comment by Leksat** [comment]
Updating `pnpm/action-setup` to `v4` solved the issue for me ✅

**Comment by Johnnasimba** [comment]
I am facing the same issue. Has anyone found a solution yet 
![Screenshot 2024-07-04 at 12 07 37](https://github.com/pnpm/pnpm/assets/61520163/40a448e3-3e84-4caa-98fb-c848ed85a407)

**Comment by ekwoka** [comment]
@Johnnasimba 

there is a solution literally one comment before yours.

**Comment by comatory** [comment]
I was on `v2` and was getting the same error, we bumped to `3.0.0` just to be sure. I still fail to understand the root cause since last release of `v2` was in July 2023 and it worked fine until today.

I guess some other dependency or other CI environment settings must be causing it.

**Comment by noudadrichem** [comment]
Would love to know how this is suddenly happening for so many people.

**Comment by Johnnasimba** [comment]
> I'm facing the same issue, has anyone found a solution yet ![Screenshot 2024-07-04 at 12 47 32](https://private-user-images.githubusercontent.com/61520163/345803742-bf71c460-dfa2-45a8-b075-97b3155e3f0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDM0NDQsIm5iZiI6MTcyMDEwMzE0NCwicGF0aCI6Ii82MTUyMDE2My8zNDU4MDM3NDItYmY3MWM0NjAtZGZhMi00NWE4LWIwNzUtOTdiMzE1NWUzZjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE0MjU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTk5ZjkyOGNlYjYxZTA2MjQ4NGViODAxOTg3Y2VlMzU1ZjNjZTVmNzVhMGY5YzZjOTBlMGI5NWQ1Y2QyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CMt-mvWtvqBDJljJccdipJsL6O-qNbKjKNbOjq3rPtU)

I changed to v4, issue resolved

**Comment by GabrielMerigo** [comment]
Updating `pnpm/action-setup` to `v4` worked for me as well.

**Comment by justin-caldicott** [comment]
Literally just started using this yesterday and hit this. Bad timing!! Thanks for the solution - `v4` sorted it.

**Comment by darklightblue** [comment]
> Updating pnpm/action-setup to v4 worked for me as well.

This worked for me, the error only happened a few hours ago

**Comment by timbrunette** [comment]
I believe this might actually be related to this github actions issue, the timing seems aligned here 
https://github.com/actions/checkout/issues/1809#issuecomment-2208202462

**Comment by zkochan** [comment]
Fixed in 2.4.1 https://github.com/pnpm/action-setup/releases/tag/v2.4.1

Locking this issue as it was related to the action not pnpm itself.

Related issue in the action: https://github.com/pnpm/action-setup/issues/135
