### ISSUE TITLE
pnpm self-update fails on Windows 11 (EPERM: operation not permitted, unlink)

### ISSUE THREAD

**Issue by frankhale** [pnpm/pnpm#9187]
### Verify latest release

- [ ] I verified that the issue exists in the latest pnpm release

### pnpm version

10.5.1

### Reproduction steps

pnpm self-update

### Describe the Bug

Running `pnpm self-update` on Windows 11 results in an error saying that because pnpm.exe already exists it cannot be unlinked. I tried this using powershell opened in Administrator mode.

Looks like it's recommended to use other means to install pnpm on Windows so I am moving away from using the Powershell install. Didn't realize there were other ways to install since the Powershell method is at the top of the "Getting Started" page.

```
Nothing to stop. No server is running for the store at C:\Users\frank\AppData\Local\pnpm\store\v10
 WARN  The target bin directory already contains an exe called pnpm, so removing C:\Users\frank\AppData\Local\pnpm\pnpm.EXE
 EPERM  EPERM: operation not permitted, unlink 'C:\Users\frank\AppData\Local\pnpm\pnpm.EXE'
```

<img width="889" alt="Image" src="https://github.com/user-attachments/assets/3bd8f659-fc93-417a-b8e9-fc268ccf59c0" />

### Expected Behavior

pnpm self-update should update to the latest version as expected

### Which Node.js version are you using?

22.14.0

### Which operating systems have you used?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by AstroGD** [comment]
Same issue here on Windows with pnpm 10.4.1 and NodeJS 22.13.1 and Windows

**Comment by thebjorn** [comment]
Can confirm Windows 11, node 23.7.0, pnpm 10.5.2.

**Comment by hfournier** [comment]
Same here on
- Windows 11 (ARM) (26100.3194)
- pnpm 9.15.2
- node 22.11.0

**Comment by zkochan** [comment]
Does this happen because the pnpm CLI that is being removed is the one running?

**Comment by hfournier** [comment]
For me, I get a notification that there's a new version available, including the line needed to update it. I copy and paste the line and get the error. I've tried both CMD and Powershell, including as Admin, same result.

**Comment by zkochan** [comment]
We should fix it.

In the meantime, maybe it works better via WinGet? https://pnpm.io/installation#using-winget

**Comment by hfournier** [comment]
I tried using npm (in CMD) and winget (in CMD and PowerShell as Admin), which didn't produce any error, but  `pnpm -v` still returns: 9.15.2. 

<img width="675" alt="Image" src="https://github.com/user-attachments/assets/5d5c9ebb-7686-43c5-8ea0-7ed341adf693" />

even after restarting the console.

Also tried 'pnpm self-update' in PowerShell as admin:

<img width="675" alt="Image" src="https://github.com/user-attachments/assets/f2e4a5bb-345b-438b-9901-d2882b8c0fdf" />

**Comment by gonza182ny** [comment]
Im having same issue. Windows 10. Going from 10.3.0 to 10.6.2

**Comment by frankhale** [comment]
I think if you are on Windows the best way to install is with npm at least for now until the issues are resolved. My guess is, since pnpm is running the OS has it locked so the self-update won't work because it won't be able to replace itself since it's locked by the OS. Since I've switched and installed it with npm I've had no issues updating it when new releases come out.

**Comment by hfournier** [comment]
I tried using npm and winget, both ran without error, but when I did `pnpm -v`, it still showed 9.15.2

I ended up going into `c:\users\XXXXXXXX\AppData\local\pnpm\` and renaming `pnpm.exe`. I was then able to install `pnpm` via `npm`. 

It now shows version 10.6.3

What a PITA. 

Surprisingly, I did not get a new `pnpm.exe` in the above mentioned folder. So, I'm not sure where it's installed now.

**Comment by thebjorn** [comment]
> I think if you are on Windows the best way to install is with npm at least for now until the issues are resolved. 

If you're not working with this every day it is confusingly many ways to install pnpm (corepack/npm/winget/chocolatey/..?)
And each installation method comes with its own upgrade command line. I can remember `pnpm self-update`, but I have no idea what the corepack version is(..?) It is therefore very nice that the right upgrade command is  printed to the terminal... except in cases like this where you're left with half an installation. The suckiness of that can not be overstated.

We spent a good 3-4 hours on identifying the problem, trying to find ways to force the install to go through, finding a previous version that was relatively painless to go to (that was/is `pnpm@9.1.1`  for us), and running the changes out to devs and pipelines. I'm guessing the other ~64% of developers who develop on windows (https://www.jetbrains.com/lp/devecosystem-2023/development/) faced the same issue.

The frustration was real (all development stopped early in the am when the devs came in and updated their systems).

Since I was the one who mandated use of pnpm, I also got comments like "why aren't we just using npm/yarn/bun?", "if pnpm can't even install itself, can we trust it will get our package installs correct?", and a few more that had more frustration and less substance.

I see that windows-latest is a part of the pnpm pipelines (yay!), but I couldn't find (my search-fu is admittedly weak today...) tests that installed (in all the flavors) previous versions and updated to the latest. That might be useful to have?

It is really difficult to trust that this will not happen again (I'm sorry, but considering the frustration it caused this is just facts), and I'm afraid our v9.1.1 locked version will stay in place for a very long time - someone will have to find time to sacrifice their development setup to test a new fixed version... :-( 

> My guess is, since pnpm is running the OS has it locked so the self-update won't work because it won't be able to replace itself since it's locked by the OS.

Which is the only sane thing to do. Why linux feels it is not a security issue that a process can delete itself from disk is a mystery...

**Comment by kadirmetin** [comment]
I get the same error when using “pnpm self-update”.

![Image](https://github.com/user-attachments/assets/2a3ef121-19ab-4cac-8564-44b3be067e81)

**Comment by cp-bwg** [comment]
The issue is likely because, if like me, you have pnpm install twice - one as local user, and another globally.  
`
$ where pnpm
C:\Users\USERNAME\AppData\Local\pnpm\pnpm.exe
C:\Users\USERNAME\AppData\Roaming\npm\pnpm
C:\Users\USERNAME\AppData\Roaming\npm\pnpm.cmd
`
When I deleted all these folders, and ran: 
`
npm install -g pnpm
`

or, it already intalled globally:

`
pnpm self-update
`

Everything worked fine.
