### ISSUE TITLE
Looks like pnpm CLI is missing at \pnpm\.tools\

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#9192]
> Same error with pnpm@10.4.1
> Failed to switch pnpm to v9.8.0. Looks like pnpm CLI is missing at "C:\Users\criit\AppData\Local\pnpm\.tools\@pnpm+win-x64\9.8.0\bin" or is incorrect
> 
> UPD: Fixed switching to 9.8.0 with https://pnpm.io/installation#using-corepack 

 _Originally posted by @crutch12 in [#9046](https://github.com/pnpm/pnpm/issues/9046#issuecomment-2668683297)_

**Comment by zkochan** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/9196

**Comment by ben-xD** [comment]
This doesn't seem solved in the latest 10.6.1

![Image](https://github.com/user-attachments/assets/a1c29048-0ce3-494c-ac0b-8a35529fd3d7)

**Comment by ppipada** [comment]
I got this when upgrading from 10.2.0 to 10.7.1 in a corepack based installation. 

Steps to resolve:
- remove the dir: i.e `rm -rf <path>/pnpm/.tools/pnpm/10.7.1`
- `corepack install -g pnpm@10.7.1`
- `corepack use pnpm@10.7.1`
- check that the installation is successful `pnpm --version`

**Comment by codeflorist** [comment]
I now have the same problem with v11.1.3. There simply is no `bin` subfolder in `AppData\Local\pnpm\.tools\@pnpm+win-x64\11.1.3`, no matter what i do. 🫤

On the other hand i suddenly have a `AppData\Local\pnpm\.tools\@pnpm+exe`, folder, which wasn't there before, which has a `11.1.3` sobfolder, that actually HAS a `bin` folder. But that folder doesn't seem to be used. 🤷‍♂️

**Comment by arnaudrenaud** [comment]
> I now have the same problem with v11.1.3. There simply is no `bin` subfolder in `AppData\Local\pnpm\.tools\@pnpm+win-x64\11.1.3`, no matter what i do. 🫤
> 
> On the other hand i suddenly have a `AppData\Local\pnpm\.tools\@pnpm+exe`, folder, which wasn't there before, which has a `11.1.3` sobfolder, that actually HAS a `bin` folder. But that folder doesn't seem to be used. 🤷‍♂️

Exactly the same issue (with 11.5.2, macOS ARM). Deleting the directory and reinstalling with `corepack install -g pnpm@11.5.2` does not fix the issue.

**Comment by arnaudrenaud** [comment]
Finally fixed it with :

```sh
rm -rf  ~/Library/pnpm
npm uninstall -g corepack
npm i -g corepack
corepack use pnpm@latest
```
